using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Immutable;
using System.Text;

namespace Sanet.MakaMek.SourceGenerators;

[Generator]
public class MovementCostTypeResolverGenerator : IIncrementalGenerator
{
    private const string BaseTypeFullName = "Sanet.MakaMek.Map.Models.MovementCosts.MovementCost";
    private const string BaseTypeNamespace = "Sanet.MakaMek.Map.Models.MovementCosts";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var derivedTypes = context.CompilationProvider.Select(static (compilation, _) =>
        {
            try
            {
                var movementCostSymbol = compilation.GetTypeByMetadataName(BaseTypeFullName);
                if (movementCostSymbol is null)
                    return ImmutableArray<TypeInfo>.Empty;

                var result = new List<TypeInfo>();
                var visited = new HashSet<IAssemblySymbol>(SymbolEqualityComparer.Default);

                var currentAssembly = compilation.Assembly;
                if (visited.Add(currentAssembly))
                    CollectDerivedTypes(currentAssembly.GlobalNamespace, movementCostSymbol, result);

                var baseAssembly = movementCostSymbol.ContainingAssembly;
                if (baseAssembly is not null && visited.Add(baseAssembly))
                    CollectDerivedTypes(baseAssembly.GlobalNamespace, movementCostSymbol, result);

                return result.ToImmutableArray();
            }
            catch
            {
                return ImmutableArray<TypeInfo>.Empty;
            }
        });

        context.RegisterSourceOutput(derivedTypes, static (spc, types) =>
        {
            try
            {
                var source = types.Length > 0
                    ? GenerateTypeResolverExtension(BaseTypeNamespace, [.. types])
                    : GenerateEmptyTypeResolverExtension(BaseTypeNamespace);
                spc.AddSource("MovementCostTypeResolverExtension.g.cs", SourceText.From(source, Encoding.UTF8));
            }
            catch (Exception ex)
            {
                spc.ReportDiagnostic(Diagnostic.Create(
                    new DiagnosticDescriptor("MCTRG001", "Source generator error",
                        $"Error in MovementCostTypeResolverGenerator: {ex.Message}\nStack trace: {ex.StackTrace}",
                        "SourceGenerator",
                        DiagnosticSeverity.Error, true),
                    Location.None));
            }
        });
    }

    private static void CollectDerivedTypes(INamespaceOrTypeSymbol parent, INamedTypeSymbol baseType,
        List<TypeInfo> result)
    {
        foreach (var member in parent.GetMembers())
        {
            if (member is INamespaceOrTypeSymbol child)
            {
                if (child is INamedTypeSymbol { IsAbstract: false } namedType
                    && InheritsFrom(namedType, baseType))
                {
                    result.Add(new TypeInfo(
                        namedType.Name,
                        namedType.ContainingNamespace.ToDisplayString(),
                        namedType.ToDisplayString()));
                }

                CollectDerivedTypes(child, baseType, result);
            }
        }
    }

    private class TypeInfo(string name, string ns, string fullName)
    {
        public string Name { get; } = name;
        public string Namespace { get; } = ns;
        public string FullName { get; } = fullName;
    }

    private static bool InheritsFrom(INamedTypeSymbol typeSymbol, INamedTypeSymbol baseTypeSymbol)
    {
        if (typeSymbol.BaseType != null &&
            SymbolEqualityComparer.Default.Equals(typeSymbol.BaseType, baseTypeSymbol))
        {
            return true;
        }

        var currentSymbol = typeSymbol.BaseType;
        while (currentSymbol != null)
        {
            if (SymbolEqualityComparer.Default.Equals(currentSymbol, baseTypeSymbol))
                return true;

            if (currentSymbol is { IsGenericType: true })
            {
                if (SymbolEqualityComparer.Default.Equals(currentSymbol.ConstructedFrom, baseTypeSymbol))
                    return true;
            }

            currentSymbol = currentSymbol.BaseType;
        }

        foreach (var interfaceSymbol in typeSymbol.AllInterfaces)
        {
            if (SymbolEqualityComparer.Default.Equals(interfaceSymbol, baseTypeSymbol))
                return true;
        }

        return false;
    }

    private static string GenerateTypeResolverExtension(string movementCostNamespace, List<TypeInfo> derivedTypes)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Text.Json;");
        sb.AppendLine("using System.Text.Json.Serialization;");
        sb.AppendLine("using System.Text.Json.Serialization.Metadata;");
        sb.AppendLine($"using {movementCostNamespace};");

        var namespaces = derivedTypes
            .Select(t => t.Namespace)
            .Distinct()
            .Where(ns => ns != movementCostNamespace)
            .OrderBy(ns => ns);

        foreach (var ns in namespaces)
        {
            sb.AppendLine($"using {ns};");
        }

        sb.AppendLine();
        sb.AppendLine("namespace Sanet.MakaMek.Core.Data.Serialization");
        sb.AppendLine("{");
        sb.AppendLine("    public partial class MovementCostTypeResolver");
        sb.AppendLine("    {");
        sb.AppendLine("        protected override void RegisterGeneratedTypes(JsonTypeInfo jsonTypeInfo)");
        sb.AppendLine("        {");

        foreach (var derivedType in derivedTypes.OrderBy(t => t.Name))
        {
            sb.AppendLine(
                $"            jsonTypeInfo.PolymorphismOptions.DerivedTypes.Add(new(typeof({derivedType.FullName}), \"{derivedType.Name}\"));");
        }

        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string GenerateEmptyTypeResolverExtension(string movementCostNamespace)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using System.Text.Json.Serialization.Metadata;");
        sb.AppendLine($"using {movementCostNamespace};");
        sb.AppendLine();
        sb.AppendLine("namespace Sanet.MakaMek.Core.Data.Serialization");
        sb.AppendLine("{");
        sb.AppendLine("    public partial class MovementCostTypeResolver");
        sb.AppendLine("    {");
        sb.AppendLine("        protected override void RegisterGeneratedTypes(JsonTypeInfo jsonTypeInfo)");
        sb.AppendLine("        {");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}