name: MekForge Avalonia Library
on:
  push:
    branches:
      - main
  pull_request:

  workflow_dispatch:
env:
  NuGetDirectory: ${{ github.workspace}}/nuget
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.x

      - name: Run Avalonia tests
        run: dotnet test tests/MekForge.Avalonia.Tests/MekForge.Avalonia.Tests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:ExcludeByAttribute=GeneratedCodeAttribute /p:Include=[Sanet.MekForge.Avalonia]Sanet.MekForge.Avalonia.Converters*,[Sanet.MekForge.Avalonia]Sanet.MekForge.Avalonia.Game*

      - name: Upload coverage report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: tests/MekForge.Avalonia.Tests/coverage.opencover.xml
          if-no-files-found: error

      - name: Upload Avalonia tests results
        run: bash <(curl -s https://codecov.io/bash) -f "tests/MekForge.Avalonia.Tests/coverage.opencover.xml" -t ${{ secrets.CODECOV_TOKEN }}
  
  publish-nuget:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.x'

      - name: Create nuget packages
        run: |
          dotnet pack src/MekForge.Avalonia/MekForge.Avalonia/MekForge.Avalonia.csproj --configuration Release --output ${{ env.NuGetDirectory }}

      - name: Publish NuGet package
        run: |
          for file in "${{ env.NuGetDirectory }}"/*.nupkg; do
            dotnet nuget push "$file" --api-key "${{ secrets.NUGET_APIKEY }}" --source https://api.nuget.org/v3/index.json --skip-duplicate
          done
