name: Sync Docs to Wiki

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - '.github/workflows/sync-docs-to-wiki.yml'

jobs:
  sync-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Clone Wiki repository
        run: |
          git clone https://x-access-token:${{ secrets.GH_WIKI_TOKEN }}@github.com/anton-makarevich/MakaMek.wiki.git wiki

      - name: Sync docs to wiki
        run: |
          rsync -av --delete docs/ wiki/
          cd wiki
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Sync docs from main repo [skip ci]" || echo "No changes to commit"
          git push
  